version: '3'


services:
  nginx-harden:
    image: nginx:latest
    ports:
      - "8443:443" # Need to change port to the proper port later
      - "8000:80" # Need to change the port the proper port later
    volumes:
      - ./etc/default.conf:/etc/nginx/conf.d/default.conf
      - ./etc/localhost.pem:/etc/nginx/localhost.pem
      - ./etc/localhost.key:/etc/nginx/localhost.key
      - ./etc/dhparams.pem:/etc/nginx/dhparams.pem
      - ./etc/security-configs.conf:/etc/nginx/security-configs.conf
      - ./etc/cors-headers.conf:/etc/nginx/cors-headers.conf
      - ./html/index.html:/usr/share/nginx/html/index.html
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 3s
      retries: 3
      # start_period: 40s # for docker-compose version 3.4 or higher  

